project:
  type: website
  output-dir: docs
  render:
    - syllabus.qmd
    - slides.qmd
    - html/*.qmd
  resources:
    - CNAME
    - pdf/*.pdf
    - index.html
    - under-construction.html

website:
  title: ""
  search: false
  navbar:
    search: false
    title: MGMT 803
    left:
      - href: index.html
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: slides.qmd
        text: Slides

format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true
