project:
  type: website
  output-dir: docs
  render:
    - syllabus.qmd
    - slides/part*.qmd
  resources:
    - CNAME
    - pdf/*.pdf
    - files/part*/*.csv
    - files/part*/*.zip
    - files/part*/*.md
    - index.html
    - slides/cosine.html
    - under-construction.html
    - breakouts.html
    - wheel.html

website:
  title: ""
  search: false

format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true
